#! /usr/bin/bash

(* #to read name at the same line *)
read -p "username: " username 

(* password format input + same line *)
read -sp "password: " password 
echo "username: $username password: $password"

read age
echo $age


________________________________________________________________________________ conditional statement _________________________________________________________________________


count=1

if [ $count -eq 10 ]
then
    echo "The value is true" 
elif ((count == 1))
    echo "it's one"
else 
    echo "it's not 10"
fi

(* # another format *)

if(($count == 10))
then 
    echo "it's 10"
elif ((count == 1))
    echo "it's one"
else 
echo "it's not 10"
fi

_________________________________________________________________________________ file test operators ____________________________________________________________________

(* # This will check wheather file exists or not *)

echo -e "Enter the name of the file: \c"
read file_name


(* -f for regular file, -d for dir/folder *)

if [ -e $file_name ]
then
echo "The file exists on the system"
else 
echo "not found"
fi

__________________________________________________________________ append output to the end of text file _____________________________________________________________

echo -e "Enter filename: \c"
read file_name

if [ -f $file_name ]
then
    if [ -w $file_name ]
    then
       echo "Enter what you want to write. ctrl + d to exit"
(*     #    > sign is for override btw *)
       cat >> $file_name 
    else
        echo "Permission missing"
    fi
else
echo "$file_name doesn't exist"
fi


